# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sharing thoughts on software craftsmanship
email: castanho.jfc@gmail.com
description: >-
  Francisco's articles on software craftsmanship
baseurl: ""
url: "franciscocastanho.pt"
twitter_username: castanhojfc
github_username: castanhojfc
linkedin_username: francisco-castanho-5ab21945
search: true
repository: "castanhojfc/website"
logo: /assets/images/logo.png

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Lisbon

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Francisco Castanho"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Software Engineer at Onfido."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/francisco-castanho-5ab21945/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/castanhojfc"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/castanhojfc"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/francisco-castanho-5ab21945/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/castanhojfc"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/castanhojfc"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      author: "Francisco Castanho"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
